### ISSUE TITLE
not issue only a question

### ISSUE THREAD

**Issue by DAVIZINH0** [loick111/dash-domoticz#2]
Hello,
This is not issue but i dont know how to make you a question :-)

I use your container and works perfect months ago.
Yesterday I change my router and the network interface on the nas. all the dockers works perfect and no issues.
But i have a problem with the dashbuttons. The docker not detects anny button.
i can see in the router that the button conect to wifi when i push it, but the docker not detect nothing.
Do you know if there is some thing special that cause this problem??

thanks a lot and sorry for this inusual contact method!

**Comment by loick111** [comment]
Hello!
Hope you fixed your problem, but in case you are still having this issue, I will recommend you make sure you are using the docker `host` network.
https://docs.docker.com/network/host/

Have a good day :)

**Comment by DAVIZINH0** [comment]
yes, the docker is in the host network. but i dont know where is the problem. i stop using the dash button and migrate to zigbee buttons.
thanks anyway
